export const gender = [
  { label: "Male" },
  { label: "Female" },
  { label: "Others" },
];

export const education = [
  { label: "B.Tech" },
  { label: "B.Sc" },
  { label: "BBA" },
  { label: "BComm" },
  { label: "BEd" },
  { label: "BE" },
  { label: "LLB" },
  { label: "B Pharma" },
  { label: "M.B.B.S" },
];

export const profession = [
  { label: "Engineer" },
  { label: "Business" },
  { label: "Doctor" },
];

export const states = [
  { label: "Andhra Pradesh" },
  { label: "Arunachal Pradesh" },
  { label: "Assam" },
  { label: "Bihar" },
  { label: "Chhattisgarh" },
  { label: "Delhi [National Capital Territory (NCT)]" },
  { label: "Goa" },
  { label: "Gujarat" },
  { label: "Haryana" },
  { label: "Himachal Pradesh" },
  { label: "Jharkhand" },
  { label: "Karnataka" },
  { label: "Kerala" },
  { label: "Maharashtra" },
  { label: "Madhya Pradesh" },
  { label: "Manipur" },
  { label: "Meghalaya" },
  { label: "Mizoram" },
  { label: "Nagaland" },
  { label: "Odisha" },
  { label: "Punjab" },
  { label: "Rajasthan" },
  { label: "Sikkim" },
  { label: "Tamil Nadu" },
  { label: "Tripura" },
  { label: "Telangana" },
  { label: "Uttar Pradesh" },
  { label: "West Bengal" },
  { label: "Andaman & Nicobar (UT)" },
  { label: "Chandigarh (UT)" },
  { label: "Dadra & Nagar Haveli and Daman & Diu (UT)" },
  { label: "Jammu & Kashmir (UT)" },
  { label: "Ladakh (UT)" },
  { label: "Lakshadweep (UT)" },
  { label: "Puducherry (UT)" },
];

export const country = [{ label: "India" }, { label: "NRI" }];

export const childGender = [
  { label: "Male" },
  { label: "Female" },
  { label: "Others" },
];

export const initialState = {
  firstName: "",
  middleName: "",
  lastName: "",
  dob: "",
  mobileNumber: "",
  email: "",
  gender: "",
  profession: "",
  education: "",
  address: "",
  address2: "",
  pincode: "",
  state: "",
  country: "",
  fatherName: "",
  motherName: "",
  spouseName: "",
  spouseAge: "",
  spouseGender: "",
  spouseProfession: "",
  spouseEducation: "",
  nativeAddress: "",
  noOfChildren: "",
  nameOfChild: "",
  ageOfChild: "",
  childGender: "",
  aadharNumber: "",
  voterId: "",
  introduction: "",
  description: "",
  presentOccupation: "",
  referenceOne: "",
  referenceTwo: "",
  membershipType: "",
};
